version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm set //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test