const ACCOUNT = {
	CREATE: 'CREATE_ACCOUNT',
	CREATE_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
	CREATE_ERROR: 'CREATE_ACCOUNT_ERROR',

	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_ERROR: 'LOGIN_ERROR',

	LOGOUT: 'LOGOUT',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_ERROR: 'LOGOUT_ERROR',
};

export default ACCOUNT;
